CREATE TABLE IF EXISTS setLatitude;
CREATE TABLE IF EXISTS setLongitude;


CREATE TABLE setLongitude (
lon INT FLOAT UNSIGNED NOT NULL
PRIMARY KEY (lat)

CREATE TABLE setLatitude
lat INT FLOAT UNSIGNED NOT NULL
PRIMARY KEY (lon)

